// Generated by LiveScript 1.3.0
(function(){
  var chainCtrl;
  chainCtrl = function($scope){
    $scope.myFolder = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'];
    $scope.myI = 0;
    $scope.myJ = 0;
  };
  angular.module('chainApp', []).controller('chainCtrl', chainCtrl);
}).call(this);
