// Generated by LiveScript 1.3.0
(function(){
  var chainCtrl, myDummy;
  chainCtrl = function($window, $scope, $dummy, $goban){
    $scope.goban = $goban;
    $scope.goban.data = $dummy;
    $scope.goban.load($goban.myI);
    $scope.navHeight = 50;
    $scope.countHeight = function(){
      return $window.innerHeight - 40;
    };
    $scope.countWidth = function(){
      return $window.innerWidth;
    };
  };
  myDummy = {
    name: '赤皮仔',
    isFolder: false,
    url: 'https://autolearn.hackpad.com/33EfKKhNtF8'
  };
  angular.module('chainApp', ['goban']).constant('$gobanPath', 'https://ethercalc.org/').constant('$gobanTitle', 'bt_frontend').constant('$gobanMax', 6).constant('$dummy', myDummy).controller('chainCtrl', chainCtrl);
}).call(this);
